### PR TITLE
Hipm 286 time slider

### PR DESCRIPTION
**Pull request by zlatna**

### CODE REVIEW

**Review by NiWe90 — CHANGES_REQUESTED** [review]
- Dots of timeslider should be bigger
- no fading effect between the images
- no labels under the dots

**Comment by zlatna** [comment]
- The time slider is provided by a MaterialControls library, this is what we have. In iOS the slider should NOT look this way at all, i.e. these slider separation by dots or whatever else should not be visible.
- i don't see any fading effect on the android app (at least on my phone)
- i don't see any numbers under the dots in the android app (at least on my phone)

**Comment by NiWe90** [comment]
with fading effect i mean when you move the time slider, one images is faded out and the next is faded in...so the next images is blend in like that:
unbenannt

regarding the numbers you are right...i thought there were numbers... sorry

**Comment by zlatna** [comment]
In my opinion this should be logged as bug. It also doesn't appear as acceptance criteria.

**Review by NiWe90 — APPROVED** [review]

**Pull request merged**
